Coding:
- 'Untitled - Google Chrome'
- 'Visual Studio Code'
- 'Sublime'
- '- gedit'
- 'Tilix: Default'
Reading:
- 'Mendeley Desktop'
Browsing:
- 'Google Chrome'
- 'Firefox'
Locked:
- 'Screen is locked'
